"""initial schema

Tables (spec entity; PII columns):
- users: User; PII users.email, users.display_name, users.phone
- vendor_accounts: VendorAccount; contact_email is business contact, no resident PII
- requests: Permit request (Request); no direct PII (organizer via users)
- signatures: Petition signature; PII signatures.name, signatures.house_number, signatures.email
- paper_petitions: PaperPetition attestation; PII paper_petitions.file_ref (scanned sheet)
- change_requests: ChangeRequest (reschedule/cancel); free-text message only
- offers: Vendor Offer; no PII
- matches: Match (request <-> vendor offer); no PII
- threads: Thread (request/job conversation); no PII
- messages: Message; PII messages.body (free text)
- weekend_slots: WeekendSlot capacity counter; no PII
- notifications: Notification outbox; payload may hold recipient details, no dedicated PII column
- audit_logs: AuditLog; before/after JSON snapshots, no dedicated PII column

Revision ID: bb5ba39144e4
Revises: 
Create Date: 2026-10-03 13:55:04.615201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5ba39144e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_entity_entity_id', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel IN ('email', 'sms')", name=op.f('ck_notifications_channel')),
    sa.CheckConstraint("status IN ('queued', 'sent', 'failed')", name=op.f('ck_notifications_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_table('vendor_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('invited', 'approved', 'suspended')", name=op.f('ck_vendor_accounts_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_accounts'))
    )
    op.create_table('weekend_slots',
    sa.Column('weekend_key', sa.String(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('approved_count >= 0', name=op.f('ck_weekend_slots_approved_count_nonneg')),
    sa.PrimaryKeyConstraint('weekend_key', name=op.f('pk_weekend_slots'))
    )
    op.create_table('offers',
    sa.Column('vendor_account_id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('jobs_per_day', sa.Integer(), nullable=False),
    sa.Column('includes', sa.String(length=300), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('zips', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("service IN ('ice_cream', 'food_truck', 'bounce_house', 'face_painting', 'music_dj', 'other')", name=op.f('ck_offers_service')),
    sa.CheckConstraint('jobs_per_day > 0', name=op.f('ck_offers_jobs_per_day_positive')),
    sa.CheckConstraint('max_guests > 0', name=op.f('ck_offers_max_guests_positive')),
    sa.CheckConstraint('price_usd >= 0', name=op.f('ck_offers_price_nonneg')),
    sa.ForeignKeyConstraint(['vendor_account_id'], ['vendor_accounts.id'], name=op.f('fk_offers_vendor_account_id_vendor_accounts')),
    sa.PrimaryKeyConstraint('vendor_account_id', name=op.f('pk_offers'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('vendor_account_id', sa.String(), nullable=True),
    sa.Column('dev_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('resident', 'vendor', 'reviewer', 'admin')", name=op.f('ck_users_role')),
    sa.ForeignKeyConstraint(['vendor_account_id'], ['vendor_accounts.id'], name=op.f('fk_users_vendor_account_id_vendor_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('dev_token', name=op.f('uq_users_dev_token'))
    )
    op.create_table('requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizer_id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('date_start', sa.String(length=10), nullable=False),
    sa.Column('date_end', sa.String(length=10), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_date', sa.String(length=10), nullable=True),
    sa.Column('petition_token', sa.String(), nullable=True),
    sa.Column('petition_due', sa.String(length=10), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('decision_snapshot', sa.JSON(), nullable=True),
    sa.Column('rules_year', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('party')", name=op.f('ck_requests_kind')),
    sa.CheckConstraint("status IN ('draft', 'collecting', 'submitted', 'approved', 'rejected', 'withdrawn', 'cancelled', 'completed')", name=op.f('ck_requests_status')),
    sa.CheckConstraint('date_start <= date_end', name=op.f('ck_requests_date_order')),
    sa.CheckConstraint('guests > 0', name=op.f('ck_requests_guests_positive')),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], name=op.f('fk_requests_organizer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('petition_token', name=op.f('uq_requests_petition_token'))
    )
    op.create_index('ix_requests_approved_date', 'requests', ['approved_date'], unique=False)
    op.create_index('ix_requests_block_id', 'requests', ['block_id'], unique=False)
    op.create_index('ix_requests_organizer_id', 'requests', ['organizer_id'], unique=False)
    op.create_index('ix_requests_status', 'requests', ['status'], unique=False)
    op.create_index('ix_requests_submitted_at', 'requests', ['submitted_at'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('proposed_start', sa.String(length=10), nullable=False),
    sa.Column('proposed_end', sa.String(length=10), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('new_date', sa.String(length=10), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'accepted', 'declined')", name=op.f('ck_change_requests_status')),
    sa.CheckConstraint("type IN ('reschedule', 'cancel')", name=op.f('ck_change_requests_type')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_change_requests_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_requests'))
    )
    op.create_index('ix_change_requests_request_id', 'change_requests', ['request_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('vendor_account_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('why', sa.JSON(), nullable=False),
    sa.Column('price_snapshot', sa.Integer(), nullable=False),
    sa.Column('includes_snapshot', sa.String(), nullable=False),
    sa.Column('service_snapshot', sa.String(), nullable=False),
    sa.Column('needs_reconfirm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('proposed', 'accepted', 'declined', 'withdrawn', 'void')", name=op.f('ck_matches_state')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_matches_request_id_requests')),
    sa.ForeignKeyConstraint(['vendor_account_id'], ['vendor_accounts.id'], name=op.f('fk_matches_vendor_account_id_vendor_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('request_id', 'vendor_account_id', name=op.f('uq_matches_request_id'))
    )
    op.create_index('ix_matches_request_id', 'matches', ['request_id'], unique=False)
    op.create_index('ix_matches_vendor_account_id_event_date', 'matches', ['vendor_account_id', 'event_date'], unique=False)
    op.create_table('paper_petitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('address_count', sa.Integer(), nullable=False),
    sa.Column('file_ref', sa.String(), nullable=True),
    sa.Column('attested_by', sa.String(), nullable=False),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_paper_petitions_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_petitions')),
    sa.UniqueConstraint('request_id', name=op.f('uq_paper_petitions_request_id'))
    )
    op.create_table('signatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('counted', 'duplicate_address', 'off_block', 'struck')", name=op.f('ck_signatures_state')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_signatures_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signatures'))
    )
    op.create_index('ix_signatures_request_id', 'signatures', ['request_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.CheckConstraint("kind IN ('request', 'job')", name=op.f('ck_threads_kind')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_threads_match_id_matches')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_threads_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads'))
    )
    op.create_index('ix_threads_request_id', 'threads', ['request_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('author_role', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("author_role IN ('resident', 'vendor', 'village')", name=op.f('ck_messages_author_role')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_messages_author_id_users')),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_messages_thread_id_threads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_thread_id_created_at', 'messages', ['thread_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_thread_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_threads_request_id', table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_signatures_request_id', table_name='signatures')
    op.drop_table('signatures')
    op.drop_table('paper_petitions')
    op.drop_index('ix_matches_vendor_account_id_event_date', table_name='matches')
    op.drop_index('ix_matches_request_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_change_requests_request_id', table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index('ix_requests_submitted_at', table_name='requests')
    op.drop_index('ix_requests_status', table_name='requests')
    op.drop_index('ix_requests_organizer_id', table_name='requests')
    op.drop_index('ix_requests_block_id', table_name='requests')
    op.drop_index('ix_requests_approved_date', table_name='requests')
    op.drop_table('requests')
    op.drop_table('users')
    op.drop_table('offers')
    op.drop_table('weekend_slots')
    op.drop_table('vendor_accounts')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_logs_entity_entity_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
